#!/bin/bash
gcc -g -std=gnu99 -fstack-protector-strong -o enc_server enc_server.c
gcc -std=gnu99 -fstack-protector-strong -o enc_client enc_client.c
gcc -std=gnu99 -fstack-protector-strong -o dec_server dec_server.c
gcc -std=gnu99 -fstack-protector-strong -o dec_client dec_client.c
gcc -std=gnu99 -fstack-protector-strong -o keygen keygen.c

